################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/fft.c \
../Core/Src/gui.c \
../Core/Src/main.c \
../Core/Src/menu.c \
../Core/Src/new_fft.c \
../Core/Src/settins.c \
../Core/Src/stm32f7xx_hal_msp.c \
../Core/Src/stm32f7xx_it.c \
../Core/Src/syscalls.c \
../Core/Src/system_stm32f7xx.c 

OBJS += \
./Core/Src/fft.o \
./Core/Src/gui.o \
./Core/Src/main.o \
./Core/Src/menu.o \
./Core/Src/new_fft.o \
./Core/Src/settins.o \
./Core/Src/stm32f7xx_hal_msp.o \
./Core/Src/stm32f7xx_it.o \
./Core/Src/syscalls.o \
./Core/Src/system_stm32f7xx.o 

C_DEPS += \
./Core/Src/fft.d \
./Core/Src/gui.d \
./Core/Src/main.d \
./Core/Src/menu.d \
./Core/Src/new_fft.d \
./Core/Src/settins.d \
./Core/Src/stm32f7xx_hal_msp.d \
./Core/Src/stm32f7xx_it.d \
./Core/Src/syscalls.d \
./Core/Src/system_stm32f7xx.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/fft.o: ../Core/Src/fft.c Core/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Core/Src/fft.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/gui.o: ../Core/Src/gui.c Core/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Core/Src/gui.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/main.o: ../Core/Src/main.c Core/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Core/Src/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/menu.o: ../Core/Src/menu.c Core/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Core/Src/menu.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/new_fft.o: ../Core/Src/new_fft.c Core/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Core/Src/new_fft.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/settins.o: ../Core/Src/settins.c Core/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Core/Src/settins.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32f7xx_hal_msp.o: ../Core/Src/stm32f7xx_hal_msp.c Core/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Core/Src/stm32f7xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32f7xx_it.o: ../Core/Src/stm32f7xx_it.c Core/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Core/Src/stm32f7xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/syscalls.o: ../Core/Src/syscalls.c Core/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Core/Src/syscalls.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/system_stm32f7xx.o: ../Core/Src/system_stm32f7xx.c Core/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Core/Src/system_stm32f7xx.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

