################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.c 

OBJS += \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.o \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.o 

C_DEPS += \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.d \
./Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.o: ../Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.c Drivers/STM32F7xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -D__FPU_PRESENT '-D__packed=__attribute__((__packed__))' '-D__weak=__attribute__((weak))' -DARM_MATH_CM7 -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Lib/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/DSP" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/GCC" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/ARM" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Drivers/CMSIS/IAR" -I../USB_DEVICE/App -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/App" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/USB_DEVICE/Target" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/inc" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/core/src" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display" -I"C:/Users/flegler.a/Desktop/Work_space/git_clone/spectrumAnalizer/Core/display/Font" -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -O0 -ffunction-sections -fdata-sections -Wall -Wfatal-errors -fstack-usage -MMD -MP -MF"Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

